// <auto-generated />
using System;
using API_IBI_01.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApplication_IBI1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240330005950_vandeir")]
    partial class vandeir
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_IBI_01.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("API_IBI_01.Models.RelatorioAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Almoco")
                        .HasColumnType("int");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("AlunoNaoTrouxe")
                        .HasColumnType("int");

                    b.Property<bool>("Atividade_EmFamilia")
                        .HasColumnType("bit");

                    b.Property<int>("CafeDaManha")
                        .HasColumnType("int");

                    b.Property<int>("CienteProfessor")
                        .HasColumnType("int");

                    b.Property<int>("CienteResponsavel")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Evacuacao")
                        .HasColumnType("int");

                    b.Property<int>("Janta")
                        .HasColumnType("int");

                    b.Property<int>("LancheDaTarde")
                        .HasColumnType("int");

                    b.Property<string>("Medicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacaoProfessor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacaoResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Repousou")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("RelatorioAlunos");
                });

            modelBuilder.Entity("API_IBI_01.Models.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Contato")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Resposaveis");
                });

            modelBuilder.Entity("WebApplication_IBI1.Models.AlunosResponsaveis", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "ResponsavelId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("AlunosResponsaveis");
                });

            modelBuilder.Entity("WebApplication_IBI1.Models.LinkDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatorioAlunoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("RelatorioAlunoId");

                    b.ToTable("LinkDto");
                });

            modelBuilder.Entity("API_IBI_01.Models.RelatorioAluno", b =>
                {
                    b.HasOne("API_IBI_01.Models.Aluno", "Aluno")
                        .WithMany("RelatorioAlunos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("WebApplication_IBI1.Models.AlunosResponsaveis", b =>
                {
                    b.HasOne("API_IBI_01.Models.Aluno", "Aluno")
                        .WithMany("Responsaveis")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_IBI_01.Models.Responsavel", "Responsavel")
                        .WithMany("Alunos")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("WebApplication_IBI1.Models.LinkDto", b =>
                {
                    b.HasOne("API_IBI_01.Models.Aluno", null)
                        .WithMany("Links")
                        .HasForeignKey("AlunoId");

                    b.HasOne("API_IBI_01.Models.RelatorioAluno", null)
                        .WithMany("Links")
                        .HasForeignKey("RelatorioAlunoId");
                });

            modelBuilder.Entity("API_IBI_01.Models.Aluno", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("RelatorioAlunos");

                    b.Navigation("Responsaveis");
                });

            modelBuilder.Entity("API_IBI_01.Models.RelatorioAluno", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("API_IBI_01.Models.Responsavel", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
